// 82s126_4a.v generated by bin2v.py

module prom_82s126_4a (dout, clk, oce, ce, reset, ad);

output [3:0] dout;
input clk;
input oce;
input ce;
input reset;
input [7:0] ad;

wire [27:0] prom_inst_0_dout_w;
wire gw_gnd;

assign gw_gnd = 1'b0;

pROM prom_inst_0 (
    .DO({prom_inst_0_dout_w[27:0],dout[3:0]}),
    .CLK(clk),
    .OCE(oce),
    .CE(ce),
    .RESET(reset),
    .AD({gw_gnd,gw_gnd,gw_gnd,gw_gnd,ad[7:0],gw_gnd,gw_gnd})
);

defparam prom_inst_0.READ_MODE = 1'b0;
defparam prom_inst_0.BIT_WIDTH = 4;
defparam prom_inst_0.RESET_MODE = "SYNC";
defparam prom_inst_0.INIT_RAM_00 = 256'hFC10E0F0000000000000000091B000007BF000005BF000003BF000001BF00000;
defparam prom_inst_0.INIT_RAM_01 = 256'hF0E0EBF01EF00000B0E0B0E00BF09350FCD0F6902C70F21000001FC0EBC0B0E0;
defparam prom_inst_0.INIT_RAM_02 = 256'h0000000000000000000000000000000000000000000000000000000000000000;
defparam prom_inst_0.INIT_RAM_03 = 256'h0000000000000000000000000000000000000000000000000000000000000000;

endmodule //prom_82s126_4a
