// 82s126_1m.v generated by bin2v.py

module prom_82s126_1m (dout, clk, oce, ce, reset, ad);

output [3:0] dout;
input clk;
input oce;
input ce;
input reset;
input [7:0] ad;

wire [27:0] prom_inst_0_dout_w;
wire gw_gnd;

assign gw_gnd = 1'b0;

pROM prom_inst_0 (
    .DO({prom_inst_0_dout_w[27:0],dout[3:0]}),
    .CLK(clk),
    .OCE(oce),
    .CE(ce),
    .RESET(reset),
    .AD({gw_gnd,gw_gnd,gw_gnd,gw_gnd,ad[7:0],gw_gnd,gw_gnd})
);

defparam prom_inst_0.READ_MODE = 1'b0;
defparam prom_inst_0.BIT_WIDTH = 4;
defparam prom_inst_0.RESET_MODE = "SYNC";
defparam prom_inst_0.INIT_RAM_00 = 256'h200135433458AB9753469ABBA9BDEEC754321100011234579ABCDDEEEDDCBA97;
defparam prom_inst_0.INIT_RAM_01 = 256'h13631583027548C726A97CEB69DB8BD707E7310137BDEDB742101247ACDEDCA7;
defparam prom_inst_0.INIT_RAM_02 = 256'h8796A5B4C3D2E1F0F0E1D2C3B4A59687788779867A857B847C837D827E817F80;
defparam prom_inst_0.INIT_RAM_03 = 256'hFEDCBA9876543210FEDCBA98765432100123456789ABCDEFFEDCBA9876543210;

endmodule //prom_82s126_1m
